name: Testing

on:
  push:
    branches:
      - 'v3'

jobs:

  put:

    runs-on: ["quix"]
    steps:
      - name: Clean up workspace
        uses: quix-it/gha-clean-workspace@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prova put 
        shell: bash
        run: |
          mkdir ./test-artifact/target
          echo "ciao" > ./test-artifact/target/$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo).txt
          ls -l /test-artifact/target

      - name: prova action put
        uses: ./
        with: 
          name: prova
          destination: put
          path: ./test-artifact
    
      
      - name: check artifact in volume
        run: | 
          tree /qstage/
  
  get:
    runs-on: ["quix"]
    needs: put
    steps:
      - name: Clean up workspace
        uses: quix-it/gha-clean-workspace@v2

      - name: Checkout
        uses: actions/checkout@v4

      - name: prova action get
        uses: ./
        with: 
          name: prova
          destination: get
          path: ./test-artifact/target

      - name: check artifact in folder
        run: | 
          ls -la ./test-artifact/target



